### ISSUE TITLE
Support Deno or Node?

### ISSUE THREAD

**Issue by ftomassetti** [LIonWeb-org/lioncore-typescript#1]
Looking at the code it seems that it contains references to Deno. Is it possible to support both it and Node in the same code base?
If not, would it make sense to support Node instead?

**Comment by dslmeinte** [comment]
I think it should be possible to support both (and maybe also https://bun.sh/) at the same time, depending on the definition of “support”. Deno has support for NPM packages, so turning the core code (not the test code) into an NPM package that can be used directly by Deno as well is certainly possible. Maybe it's even possible to ship as both NPM and Deno package as well.
(I was planning to publish https://github.com/dslmeinte/mps-json-exporter as a Deno package, which might provide insights.)

**Comment by dslmeinte** [comment]
In the meanwhile I modified another of my repos to produce a Deno-compatible package: https://github.com/dslmeinte/littoral-templates
Also: Deno has proper (non-beta/experimental) support for NPM packages since version 1.28.
Note that this doesn't mean that Deno and Node/tsc are source compatible out-of-the-box because Deno requires different paths for packages and sources to import. I haven't got a solution for that yet.

**Comment by dslmeinte** [comment]
Merged into #9.
